[package]
name = "cache-registry-reader"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
description = "UE4 CachedAssetRegistry.bin and DevelopmentAssetRegistry.bin parser and JSON exporter"
repository.workspace = true

[dependencies]
unreal_asset_base.workspace = true
unreal_helpers.workspace = true
byteorder.workspace = true
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
